### ISSUE TITLE
UI | 讓 UI 知道 API 正在甦醒中

### ISSUE THREAD

**Issue by ddio** [gcaa-org-tw/company-report-toolkit#47]
### 使用者故事

身為 `專業工人` ，我想要在畫面上看到「 API 是否活著」，以知道該等它，還是找工程師回報錯誤

### 工程解釋

由於 [Render 免費版會睡著](https://render.com/docs/free#spinning-down-on-idle)，喚醒大約須 30 秒，會讓所有 API 卡住，可能會讓使用者無法分辨現在是系統壞掉，還是伺服器整在甦醒中，所以在所有需要 API 的畫面，都加上此提醒。

### 工程需求

1. 調整 `useProfessionApi` ，讓 `useProfessionApi` 也能知道目前是否正在等待伺服器甦醒
   1. 使用 #46 的 health API
   2. 只有在網頁初始化時，才需要處理這件事（因為接下來就會用 socket.io ，連線不會斷掉，伺服器就睡不著惹...）
3. 新增一個 layout ，處理所有需要登入的畫面
   1. 當還在等伺服器時，顯示全版蓋板的 modal，提示使用者：「機器人正在甦醒中，請起來喝個水，稍待片刻」
   3. 當 health API 回來後，關掉蓋板 modal

**Comment by jojomango** [comment]
我來做這個

**Comment by ddio** [comment]
@jojomango  因為後來用了 https://app.statuscake.com ，確保 API 不會睡著，所以這張就算解囉～
